Vagrant.configure("2") do |config|

  config.vm.define "ubuntu" do |app|
    app.vm.box = "ubuntu/focal64"
    app.vm.hostname = "ubuntuHost"
    app.vm.provider :virtualbox do |vb|
      vb.memory = 1024
      vb.cpus = 2
    end

  config.vm.provision "shell", run: "always", path: "script.sh"
  end
end