ENV["VAGRANT_EXPERIMENTAL"] = "disks"
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.disk :disk, size: "300MB", name: "extra_storage_1"
  config.vm.disk :disk, size: "300MB", name: "extra_storage_2"
  config.vm.disk :disk, size: "300MB", name: "extra_storage_3"
  config.vm.disk :disk, size: "300MB", name: "extra_storage_4"
  config.vm.provision "shell", path: "script.sh"
end