Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell", inline: <<-SHELL
    mv /vagrant/mover.service /lib/systemd/system/
    systemctl daemon-reload
    systemctl start mover
    systemctl enable mover
  SHELL
end
